//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductMedia
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/", ConfigurationName="ProductMedia.MediaContentService")]
    public interface MediaContentService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="getMediaContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClassType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Decoration[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Location[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MediaContent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MediaDateModified[]))]
        System.Threading.Tasks.Task<ProductMedia.getMediaContentResponse1> getMediaContentAsync(ProductMedia.getMediaContentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getMediaDateModified", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClassType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Decoration[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Location[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MediaContent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MediaDateModified[]))]
        System.Threading.Tasks.Task<ProductMedia.getMediaDateModifiedResponse1> getMediaDateModifiedAsync(ProductMedia.getMediaDateModifiedRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class GetMediaContentRequest
    {
        
        private string wsVersionField;
        
        private string idField;
        
        private string passwordField;
        
        private string cultureNameField;
        
        private mediaTypeType mediaTypeField;
        
        private string productIdField;
        
        private string partIdField;
        
        private int classTypeField;
        
        private bool classTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=0)]
        public string wsVersion
        {
            get
            {
                return this.wsVersionField;
            }
            set
            {
                this.wsVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=1)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=3)]
        public string cultureName
        {
            get
            {
                return this.cultureNameField;
            }
            set
            {
                this.cultureNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=4)]
        public mediaTypeType mediaType
        {
            get
            {
                return this.mediaTypeField;
            }
            set
            {
                this.mediaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=5)]
        public string productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=6)]
        public string partId
        {
            get
            {
                return this.partIdField;
            }
            set
            {
                this.partIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int classType
        {
            get
            {
                return this.classTypeField;
            }
            set
            {
                this.classTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classTypeSpecified
        {
            get
            {
                return this.classTypeFieldSpecified;
            }
            set
            {
                this.classTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/")]
    public enum mediaTypeType
    {
        
        /// <remarks/>
        Image,
        
        /// <remarks/>
        Video,
        
        /// <remarks/>
        Audio,
        
        /// <remarks/>
        Document,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class ClassType
    {
        
        private int classTypeIdField;
        
        private string classTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int classTypeId
        {
            get
            {
                return this.classTypeIdField;
            }
            set
            {
                this.classTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string classTypeName
        {
            get
            {
                return this.classTypeNameField;
            }
            set
            {
                this.classTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class Decoration
    {
        
        private int decorationIdField;
        
        private string decorationNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int decorationId
        {
            get
            {
                return this.decorationIdField;
            }
            set
            {
                this.decorationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string decorationName
        {
            get
            {
                return this.decorationNameField;
            }
            set
            {
                this.decorationNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class Location
    {
        
        private int locationIdField;
        
        private string locationNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int locationId
        {
            get
            {
                return this.locationIdField;
            }
            set
            {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string locationName
        {
            get
            {
                return this.locationNameField;
            }
            set
            {
                this.locationNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class MediaContent
    {
        
        private string productIdField;
        
        private string partIdField;
        
        private string urlField;
        
        private mediaTypeType mediaTypeField;
        
        private ClassType[] classTypeArrayField;
        
        private double fileSizeField;
        
        private bool fileSizeFieldSpecified;
        
        private decimal widthField;
        
        private bool widthFieldSpecified;
        
        private decimal heightField;
        
        private bool heightFieldSpecified;
        
        private int dpiField;
        
        private bool dpiFieldSpecified;
        
        private string colorField;
        
        private Decoration[] decorationArrayField;
        
        private Location[] locationArrayField;
        
        private int decorationIdField;
        
        private bool decorationIdFieldSpecified;
        
        private string descriptionField;
        
        private bool singlePartField;
        
        private System.DateTime changeTimeStampField;
        
        private bool changeTimeStampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=0)]
        public string productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=1)]
        public string partId
        {
            get
            {
                return this.partIdField;
            }
            set
            {
                this.partIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=3)]
        public mediaTypeType mediaType
        {
            get
            {
                return this.mediaTypeField;
            }
            set
            {
                this.mediaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ClassType", IsNullable=false)]
        public ClassType[] ClassTypeArray
        {
            get
            {
                return this.classTypeArrayField;
            }
            set
            {
                this.classTypeArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double fileSize
        {
            get
            {
                return this.fileSizeField;
            }
            set
            {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fileSizeSpecified
        {
            get
            {
                return this.fileSizeFieldSpecified;
            }
            set
            {
                this.fileSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified
        {
            get
            {
                return this.widthFieldSpecified;
            }
            set
            {
                this.widthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified
        {
            get
            {
                return this.heightFieldSpecified;
            }
            set
            {
                this.heightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int dpi
        {
            get
            {
                return this.dpiField;
            }
            set
            {
                this.dpiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dpiSpecified
        {
            get
            {
                return this.dpiFieldSpecified;
            }
            set
            {
                this.dpiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=9)]
        public string color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Decoration", IsNullable=false)]
        public Decoration[] DecorationArray
        {
            get
            {
                return this.decorationArrayField;
            }
            set
            {
                this.decorationArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Location", IsNullable=false)]
        public Location[] LocationArray
        {
            get
            {
                return this.locationArrayField;
            }
            set
            {
                this.locationArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int decorationId
        {
            get
            {
                return this.decorationIdField;
            }
            set
            {
                this.decorationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool decorationIdSpecified
        {
            get
            {
                return this.decorationIdFieldSpecified;
            }
            set
            {
                this.decorationIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=13)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool singlePart
        {
            get
            {
                return this.singlePartField;
            }
            set
            {
                this.singlePartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=15)]
        public System.DateTime changeTimeStamp
        {
            get
            {
                return this.changeTimeStampField;
            }
            set
            {
                this.changeTimeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changeTimeStampSpecified
        {
            get
            {
                return this.changeTimeStampFieldSpecified;
            }
            set
            {
                this.changeTimeStampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class MediaDateModified
    {
        
        private string productIdField;
        
        private string partIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=0)]
        public string productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=1)]
        public string partId
        {
            get
            {
                return this.partIdField;
            }
            set
            {
                this.partIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class GetMediaContentResponse
    {
        
        private MediaContent[] mediaContentArrayField;
        
        private errorMessage errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MediaContent", IsNullable=false)]
        public MediaContent[] MediaContentArray
        {
            get
            {
                return this.mediaContentArrayField;
            }
            set
            {
                this.mediaContentArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=1)]
        public errorMessage errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/")]
    public partial class errorMessage
    {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMediaContentRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/", Order=0)]
        public ProductMedia.GetMediaContentRequest GetMediaContentRequest;
        
        public getMediaContentRequest1()
        {
        }
        
        public getMediaContentRequest1(ProductMedia.GetMediaContentRequest GetMediaContentRequest)
        {
            this.GetMediaContentRequest = GetMediaContentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMediaContentResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/", Order=0)]
        public ProductMedia.GetMediaContentResponse GetMediaContentResponse;
        
        public getMediaContentResponse1()
        {
        }
        
        public getMediaContentResponse1(ProductMedia.GetMediaContentResponse GetMediaContentResponse)
        {
            this.GetMediaContentResponse = GetMediaContentResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class GetMediaDateModifiedRequest
    {
        
        private string wsVersionField;
        
        private string idField;
        
        private string passwordField;
        
        private string cultureNameField;
        
        private System.DateTime changeTimeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=0)]
        public string wsVersion
        {
            get
            {
                return this.wsVersionField;
            }
            set
            {
                this.wsVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=1)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=3)]
        public string cultureName
        {
            get
            {
                return this.cultureNameField;
            }
            set
            {
                this.cultureNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=4)]
        public System.DateTime changeTimeStamp
        {
            get
            {
                return this.changeTimeStampField;
            }
            set
            {
                this.changeTimeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class GetMediaDateModifiedResponse
    {
        
        private MediaDateModified[] mediaDateModifiedArrayField;
        
        private errorMessage errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MediaDateModified", IsNullable=false)]
        public MediaDateModified[] MediaDateModifiedArray
        {
            get
            {
                return this.mediaDateModifiedArrayField;
            }
            set
            {
                this.mediaDateModifiedArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=1)]
        public errorMessage errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMediaDateModifiedRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/", Order=0)]
        public ProductMedia.GetMediaDateModifiedRequest GetMediaDateModifiedRequest;
        
        public getMediaDateModifiedRequest1()
        {
        }
        
        public getMediaDateModifiedRequest1(ProductMedia.GetMediaDateModifiedRequest GetMediaDateModifiedRequest)
        {
            this.GetMediaDateModifiedRequest = GetMediaDateModifiedRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMediaDateModifiedResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/", Order=0)]
        public ProductMedia.GetMediaDateModifiedResponse GetMediaDateModifiedResponse;
        
        public getMediaDateModifiedResponse1()
        {
        }
        
        public getMediaDateModifiedResponse1(ProductMedia.GetMediaDateModifiedResponse GetMediaDateModifiedResponse)
        {
            this.GetMediaDateModifiedResponse = GetMediaDateModifiedResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface MediaContentServiceChannel : ProductMedia.MediaContentService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MediaContentServiceClient : System.ServiceModel.ClientBase<ProductMedia.MediaContentService>, ProductMedia.MediaContentService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MediaContentServiceClient() : 
                base(MediaContentServiceClient.GetDefaultBinding(), MediaContentServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MediaServiceBinding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MediaContentServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MediaContentServiceClient.GetBindingForEndpoint(endpointConfiguration), MediaContentServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MediaContentServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MediaContentServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MediaContentServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MediaContentServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MediaContentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProductMedia.getMediaContentResponse1> ProductMedia.MediaContentService.getMediaContentAsync(ProductMedia.getMediaContentRequest1 request)
        {
            return base.Channel.getMediaContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProductMedia.getMediaContentResponse1> getMediaContentAsync(ProductMedia.GetMediaContentRequest GetMediaContentRequest)
        {
            ProductMedia.getMediaContentRequest1 inValue = new ProductMedia.getMediaContentRequest1();
            inValue.GetMediaContentRequest = GetMediaContentRequest;
            return ((ProductMedia.MediaContentService)(this)).getMediaContentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProductMedia.getMediaDateModifiedResponse1> ProductMedia.MediaContentService.getMediaDateModifiedAsync(ProductMedia.getMediaDateModifiedRequest1 request)
        {
            return base.Channel.getMediaDateModifiedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProductMedia.getMediaDateModifiedResponse1> getMediaDateModifiedAsync(ProductMedia.GetMediaDateModifiedRequest GetMediaDateModifiedRequest)
        {
            ProductMedia.getMediaDateModifiedRequest1 inValue = new ProductMedia.getMediaDateModifiedRequest1();
            inValue.GetMediaDateModifiedRequest = GetMediaDateModifiedRequest;
            return ((ProductMedia.MediaContentService)(this)).getMediaDateModifiedAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MediaServiceBinding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MediaServiceBinding))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/MediaContentService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MediaContentServiceClient.GetBindingForEndpoint(EndpointConfiguration.MediaServiceBinding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MediaContentServiceClient.GetEndpointAddress(EndpointConfiguration.MediaServiceBinding);
        }
        
        public enum EndpointConfiguration
        {
            
            MediaServiceBinding,
        }
    }
}
